version: "3.8"

services:

  backend:
    build: ./backend
    container_name: todo-backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network


networks:
  todo-network:
    driver: bridge